---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "test-python-app.fullname" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-python-app.fullname" . }}
  labels:
    {{- include "test-python-app.labels" . | nindent 4 }}
  namespace: {{ include "test-python-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-python-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-python-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /liveness
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readiness
              port: {{ .Values.service.port }}
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: AUTHOR
              value: {{ .Values.author }}